OBJS 	= 	../buffer.o ../index.o ../graph.o ../queue.o ../stack.o ../ConnectedComponents.o ../SCC.o ../hashTable.o ../JobScheduler.o ../JobQueue.o


all:	main_test.o	$(OBJS)	
	gcc	main_test.o $(OBJS) -pthread -lm -o unit_test
